### ISSUE TITLE
Timing problem

### ISSUE THREAD

**Issue by amiravni** [Nissime/Structure_Core#4]
Dear sir
The time tag of the camera and IMU are not synchronized.
Do you plan to fix it soon?

Thanks

**Comment by amiravni** [comment]
So, to fix this just replace all the places in [the code](https://github.com/Nissime/Structure_Core/blob/master/src/structure_driver.cpp) where it states: 
`msg->header.stamp.fromSec(*****.timestamp());`
to:
****.header.stamp = `ros::Time::now();`

I could fix and test it myself if only I had this camera :P

**Comment by Nissime** [comment]
Dir sir, 
Thank you for the issue. 
issue solved.
